import Head from "next/head";
import React from "react";

const Home = () => {
  return (
    <>
      <Head>
        <title>Workout App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Home</div>
    </>
  );
};

export default Home;
