import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Workout App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Workout App!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          {/* <code className={styles.code}>pages/index.tsx</code> */}
        </p>
        <div className={styles.grid}>
          <Link href="/login" className={styles.card}>
            <h2>Log In &rarr;</h2>
            <p>Click here to log in, if you already have an account.</p>
          </Link>

          <Link href="/signup" className={styles.card}>
            <h2>Sign Up &rarr;</h2>
            <p>Click here to sign up as a trainer!</p>
          </Link>

          {/* <Link href="/home" className={styles.card}>
            <h2>Our Page &rarr;</h2>
            <p>Discover more about our website.</p>
          </Link>

          <Link
            href="/features"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}>
            <h2>Coming on &rarr;</h2>
            <p>Check our latest feutures and what is on .</p>
          </Link> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <Link href="/" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </div>
  );
}
