import Head from "next/head";
import React from "react";

const Login = () => {
  return (
    <>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Login</div>
    </>
  );
};

export default Login;
